[WinEventLog://Microsoft-Windows-Sysmon/Operational]
disabled = false
index = sysmon
sourcetype = xmlwineventlog

[WinEventLog://Security]
disabled = false
index = wineventlog
sourcetype = WinEventLog:Security
